//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudentListASP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Group
    {
        public Group()
        {
            this.Students = new HashSet<Student>();
        }
        [Key]
        public int IDGroup { get; set; }
        [Index(IsUnique= true)]
        [Required(ErrorMessage= "Nazwa grupy wymagana!")]
        public string Name { get; set; }
        [Timestamp]
        public byte[] TimeStamp { get; set; }

        public override string ToString()
        {
            return this.Name;
        }
        
        public virtual ICollection<Student> Students { get; set; }
    }
}
